runtime: custom
env: flex
service: etl-parser
resources:
        cpu: 2
        memory_gb: 2.0
automatic_scaling:
        min_num_instances: 3
        max_num_instances: 20
        cool_down_period_sec: 120 # default value
        cpu_utilization:
                target_utilization: 0.9
